#!/bin/bash
# Build Agent Context Bundle
# Assembles essential documentation for AI agents into a single YAML bundle
# Target: <10K tokens total

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DOCS_DIR="$PROJECT_ROOT/docs"
PLAN_DIR="$DOCS_DIR/plan"
OUTPUT_FILE="$DOCS_DIR/_agent-bundle.yaml"

echo "Building agent context bundle..."

# Extract active rules from 00-RULES.yaml (filter out comments and structure)
echo "Extracting active rules..."
ACTIVE_RULES=$(yq eval '.rules[] | select(.severity == "hard" or .severity == "medium")' "$PLAN_DIR/00-RULES.yaml")

# Extract active decisions from unified log (status: active only)
echo "Extracting active decisions..."
ACTIVE_DECISIONS=$(awk '
  BEGIN { in_active=0; skip_header=1 }
  /^## Active Decisions/ { in_active=1; next }
  /^## / && in_active { in_active=0; next }
  in_active && /^|/ {
    if (skip_header) { skip_header=0; next }
    print
  }
' "$PLAN_DIR/01-PLAN-DECISIONS.md")

# Extract component dependencies (just the dependency lists)
echo "Extracting component dependencies..."
COMPONENT_DEPS=$(yq eval '.components[] | {id: .id, dependencies: .dependencies}' "$PLAN_DIR/component-registry.yaml")

# Build the bundle YAML
cat > "$OUTPUT_FILE" << 'EOF'
# Agent Context Bundle
# Auto-generated by scripts/build-agent-bundle.sh
# Single source of essential context for AI agents
# Target: <10K tokens

version: "1.0"
generated: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

manifest:
  # Session Starter files (load: always in 00-MANIFEST.yaml)
  session_starter:
    - plan/00-RULES.yaml
    - plan/01-PLAN-DECISIONS.md
    - plan/10-STRAT-PRD.md
    - plan/11-STRAT-BLUEPRINT.md
    - plan/30-ARCH-OVERVIEW.md
    - 1/TASKS.md
    - 1/MD.md

# Active rules (hard and medium severity only)
active_rules:
EOF

# Append active rules
echo "$ACTIVE_RULES" >> "$OUTPUT_FILE"

# Add active decisions section
cat >> "$OUTPUT_FILE" << 'EOF'

# Active decisions (from unified decision log)
active_decisions: |
EOF

echo "$ACTIVE_DECISIONS" >> "$OUTPUT_FILE"

# Add component dependencies section
cat >> "$OUTPUT_FILE" << 'EOF'

# Component dependency map
component_dependencies:
EOF

echo "$COMPONENT_DEPS" >> "$OUTPUT_FILE"

# Count tokens (rough estimate: 1 token ~ 4 characters)
TOKEN_COUNT=$(wc -c < "$OUTPUT_FILE" | awk '{print int($1/4)}')

echo "Bundle generated: $OUTPUT_FILE"
echo "Estimated token count: ~$TOKEN_COUNT"

if [ "$TOKEN_COUNT" -gt 10000 ]; then
  echo "WARNING: Bundle exceeds 10K token target ($TOKEN_COUNT tokens)"
  exit 1
else
  echo "SUCCESS: Bundle within 10K token target"
fi
